apiVersion: v1
kind: Service
metadata:
  name: {{ template "mgob.fullname" . }}
  labels:
    {{- include "mgob.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
  - port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
    protocol: TCP
    name: {{ .Values.service.name }}
  selector:
    app.kubernetes.io/name: {{ include "mgob.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
